version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php8-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html



volumes:
  php-volume: